package org.tewelle.persistent.entity;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * An entity Doctor composed of fields: id, email, name, username, password and creation/modification dates.
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the username for the table in the db.
 *
 * @author Tewelle
 */
@Entity
@Table(name = "doctors", uniqueConstraints = {@UniqueConstraint(columnNames= "username")})
public class Doctor {

  // ------------------------
  // PRIVATE FIELDS
  // ------------------------
 // @ElementCollection(targetClass=Radiograph.class)
 // private Set<Radiograph> radiographs = new HashSet<>(0);

  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)

  private long id;

  // The user's email
  @NotNull
  private String email;

  @NotNull
  private String name;

  @NotNull
  @Column(unique = true)
  private String username;
  @NotNull
  private String password;

  @NotNull
  private Date updateDate;


  @NotNull
  private Date creationDate;
  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  
  public Doctor() { }

  public Doctor(long id) {
    this.id = id;
  }
  
  public Doctor(String email, String username, String password) {
    this.email = email;
    this.username = username;
    this.password =password;
  }

  // Getter and setter methods

  public long getId() {
    return id;
  }

  public void setId(long value) {
    this.id = value;
  }

  public String getEmail() {
    return email;
  }
  
  public void setEmail(String value) {
    this.email = value;
  }
  
  public String getUsername() {
    return username;
  }

  public void setUsername(String value) {
    this.username = value;
  }


  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public void update(String username, String email,String name, String password)
  {
    this.username = username;
    this.name = name;
    this.email = email;
    this.password =password;
  }

  @PreUpdate
  public void preUpdate() {
    updateDate = new Date();
  }

  @PrePersist
  public void prePersist() {
    Date now = new Date();
    creationDate =now;
    updateDate = now;
  }


  @Override
  public String toString() {
    return String.format("[id = %d, name =%s, username = %s, email = %s, password=%s]", id, name, username, email,password);
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Date getUpdateDate() {
    return updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }

  public Date getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(Date creationDate) {
    this.creationDate = creationDate;
  }


  // @JoinTable(name = "patient_radiographs", joinColumns = { @JoinColumn(name = "patient_Id", referencedColumnName = "id") }, inverseJoinColumns = { @JoinColumn(name = "radiograph_id", table = "radiograph", referencedColumnName = "id") })

 /* public Set<Radiograph> getRadiograph() {
    return this.radiographs;
  }
  @OneToMany(mappedBy = "doctor")
  public void setRadiograph(Set<Radiograph> radiographs) {
    this.radiographs=radiographs;
  }
*/
}
